name: Code formatting
permissions:
  contents: read
on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run prettier JavaScript
        run: "npm run prettier:js"

      - name: Run prettier Markdown
        run: "npm run prettier:md"

      - name: Run stylelint
        run: "npm run stylelint"
