name: Storybook and Component Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Install playwright
        run: npx playwright install

      - name: Run Storybook tests
        run: npm run test:storybook:ci

      - name: Run vitest tests
        run: npm run test:ci
